// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNEplx2T0vwmSOSuInj9SvXZzUESAuLNg',
    appId: '1:838420877540:web:e174c09ffd903442dd9cf1',
    messagingSenderId: '838420877540',
    projectId: 'hidden-analyzer-425514-u8',
    authDomain: 'hidden-analyzer-425514-u8.firebaseapp.com',
    storageBucket: 'hidden-analyzer-425514-u8.appspot.com',
    measurementId: 'G-Q0N1HKJ4WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0YecNa0ITqZBUlU2alxWgfu_X_jWylYU',
    appId: '1:838420877540:android:70541e86942ee71ddd9cf1',
    messagingSenderId: '838420877540',
    projectId: 'hidden-analyzer-425514-u8',
    storageBucket: 'hidden-analyzer-425514-u8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcqU3ke5oZwvNUWaagxDiCUAWNvYbA3Fs',
    appId: '1:838420877540:ios:1cd5881132a0c5d5dd9cf1',
    messagingSenderId: '838420877540',
    projectId: 'hidden-analyzer-425514-u8',
    storageBucket: 'hidden-analyzer-425514-u8.appspot.com',
    iosClientId: '838420877540-3l57ro4dg03c580pqu4u45sl0qeo5psk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseConnect',
  );
}
